### ISSUE TITLE
Broken Pipeline & Website

### ISSUE THREAD

**Issue by KillianH** [paul-thebaud/phpunitgen-webapp#27]
All travis ci builds are failed because of a bad version from sonar-scanner.

Maybe it would be nice to migrate to github actions.

Also the certificate for the main site (and propably the staging also) is expired due to the  bad management of my kubernetes cluster.

I'll try to rebuild it ASAP. Maybe tomorrow during lunch time.

Sorry :(

**Comment by KillianH** [comment]
Website up and running. Pipeline still broken. (sonar + kube config)

**Comment by KillianH** [comment]
As I don't have access to the repo secrets I can't do more on github actions for the moments. The new pipeline will remove a lot of complexity from the old one

**Comment by paul-thebaud** [comment]
@KillianH tell me in MP what you need ;)

**Comment by KillianH** [comment]
Pipeline & website up and running 🎊
