### ISSUE TITLE
Is there any plan to support php 8.0

### ISSUE THREAD

**Issue by beataburczyk** [paul-thebaud/phpunitgen-webapp#32]
It's not an issue, more like a question.
Currently due to look on "php": "^7.4.7" this is a composer error. As this lib is supporting Laravel 8 I'm wondering if there is any plan to support php 8 too.

**Comment by paul-thebaud** [comment]
Hi,
Yes, we plan to support PHP 8 on the two packages and webapp.
As stated on paul-thebaud/phpunitgen-core#6 and paul-thebaud/phpunitgen-console#5, i need to wait for Roave/BetterReflection#701 to be resolved before doing anything.
I'll update those 3 issues when releasing PHP 8 support.

**Comment by paul-thebaud** [comment]
PhpUnitGen version 2.0.0 stable released with PHP 8 support.
